import numpy as np
import cv2 as cv 

cap = cv.VideoCapture(0)
width = cap.get(cv.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv.CAP_PROP_FRAME_HEIGHT)
# print(cap.get(cv.CAP_IEEE1394))
# print(cap.get(cv.CAP_PROP_BRIGHTNESS))
# print(cap.get(cv.CAP_PROP_CONTRAST))
# print(cap.get(cv.CAP_PROP_GAIN))
# print(cap.get(cv.CAP_PROP_AUTO_EXPOSURE))
def name(id):
    list_of_property = [
            "AUTO_EXPOSURE",
            "AUTO_WB",
            "BACKEND",
            "BACKLIGHT",
            "BITRATE",
            "BRIGHTNESS",
            "BUFFERSIZE",
            "CHANNEL",
            "CODEC_PIXEL_FORMAT",
            "CONTRAST",
            "CONVERT_RGB",
            "DC1394_MAX",
            "DC1394_MODE_AUTO",
            "DC1394_MODE_MANUAL",
            "DC1394_MODE_ONE_PUSH_AUTO",
            "DC1394_OFF",
            "EXPOSURE",
            "EXPOSUREPROGRAM",
            "FOCUS",
            "FORMAT",
            "FOURCC",
            "FPS",
            "FRAME_COUNT",
            "FRAME_HEIGHT",
            "FRAME_WIDTH",
            "GAIN",
            "GAMMA",
            "GIGA_FRAME_HEIGH_MAX",
            "GIGA_FRAME_OFFSET_X",
            "GIGA_FRAME_OFFSET_Y",
            "GIGA_FRAME_SENS_HEIGH",
            "GIGA_FRAME_SENS_WIDTH",
            "GIGA_FRAME_WIDTH_MAX",
            "GPHOTO2_COLLECT_MSGS",
            "GPHOTO2_FLUSH_MSGS",
            "GPHOTO2_PREVIEW",
            "GPHOTO2_RELOAD_CONFIG",
            "GPHOTO2_RELOAD_ON_CHANGE",
            "GPHOTO2_WIDGET_ENUMERATE",
            "GSTREAMER_QUEUE_LENGTH",
            "GUID",
            "HUE",
            "IMAGES_BASE",
            "IMAGES_LAST",
            "INTELPERC_DEPTH_CONFIDENCE_THRESHOLD",
            "INTELPERC_DEPTH_FOCAL_LENGTH_HORZ",
            "INTELPERC_DEPTH_FOCAL_LENGTH_VERT",
            "INTELPERC_DEPTH_LOW_CONFIDENCE_VALUE",
            "INTELPERC_DEPTH_SATURATION_VALUE",
            "INTELPERC_PROFILE_COUNT",
            "INTELPERC_PROFILE_IDX",
            "IOS_DEVICE_EXPOSURE",
            "IOS_DEVICE_FLASH",
            "IOS_DEVICE_FOCUS",
            "IOS_DEVICE_TORCH",
            "IOS_DEVICE_WHITEBALANCE",
            "IRIS",
            "ISO_SPEED",
            "MODE",
            "MONOCHROME",
            "OPENNI2_MIRROR",
            "OPENNI2_SYNC",
            "OPENNI_APPROX_FRAME_SYNC",
            "OPENNI_BASELINE",
            "OPENNI_CIRCLE_BUFFER",
            "OPENNI_FOCAL_LENGTH",
            "OPENNI_FRAME_MAX_DEPTH",
            "OPENNI_GENERATOR_PRESENT",
            "OPENNI_MAX_BUFFER_SIZE",
            "OPENNI_MAX_TIME_DURATION",
            "OPENNI_OUTPUT_MODE",
            "OPENNI_REGISTRATION",
            "OPENNI_REGISTRATION_ON",
            "PAN",
            "POS_AVI_RATIO",
            "POS_FRAMES",
            "POS_MSEC",
            "PVAPI_BINNINGX",
            "PVAPI_BINNINGY",
            "PVAPI_DECIMATIONHORIZONTAL",
            "PVAPI_DECIMATIONVERTICAL",
            "PVAPI_FRAMESTARTTRIGGERMODE",
            "PVAPI_MULTICASTIP",
            "PVAPI_PIXELFORMAT",
            "RECTIFICATION",
            "ROLL",
            "SAR_DEN",
            "SAR_NUM",
            "SATURATION",
            "SETTINGS",
            "SHARPNESS",
            "SPEED",
            "TEMPERATURE",
            "TILT",
            "TRIGGER",
            "TRIGGER_DELAY",
            "VIEWFINDER",
            "WB_TEMPERATURE",
            "WHITE_BALANCE_BLUE_U",
            "WHITE_BALANCE_RED_V",
            "XI_ACQ_BUFFER_SIZE",
            "XI_ACQ_BUFFER_SIZE_UNIT",
            "XI_ACQ_FRAME_BURST_COUNT",
            "XI_ACQ_TIMING_MODE",
            "XI_ACQ_TRANSPORT_BUFFER_COMMIT",
            "XI_ACQ_TRANSPORT_BUFFER_SIZE",
            "XI_AEAG",
            "XI_AEAG_LEVEL",
            "XI_AEAG_ROI_HEIGHT",
            "XI_AEAG_ROI_OFFSET_X",
            "XI_AEAG_ROI_OFFSET_Y",
            "XI_AEAG_ROI_WIDTH",
            "XI_AE_MAX_LIMIT",
            "XI_AG_MAX_LIMIT",
            "XI_APPLY_CMS",
            "XI_AUTO_BANDWIDTH_CALCULATION",
            "XI_AUTO_WB",
            "XI_AVAILABLE_BANDWIDTH",
            "XI_BINNING_HORIZONTAL",
            "XI_BINNING_PATTERN",
            "XI_BINNING_SELECTOR",
            "XI_BINNING_VERTICAL",
            "XI_BPC",
            "XI_BUFFERS_QUEUE_SIZE",
            "XI_BUFFER_POLICY",
            "XI_CC_MATRIX_00",
            "XI_CC_MATRIX_01",
            "XI_CC_MATRIX_02",
            "XI_CC_MATRIX_03",
            "XI_CC_MATRIX_10",
            "XI_CC_MATRIX_11",
            "XI_CC_MATRIX_12",
            "XI_CC_MATRIX_13",
            "XI_CC_MATRIX_20",
            "XI_CC_MATRIX_21",
            "XI_CC_MATRIX_22",
            "XI_CC_MATRIX_23",
            "XI_CC_MATRIX_30",
            "XI_CC_MATRIX_31",
            "XI_CC_MATRIX_32",
            "XI_CC_MATRIX_33",
            "XI_CHIP_TEMP",
            "XI_CMS",
            "XI_COLOR_FILTER_ARRAY",
            "XI_COLUMN_FPN_CORRECTION",
            "XI_COOLING",
            "XI_COUNTER_SELECTOR",
            "XI_COUNTER_VALUE",
            "XI_DATA_FORMAT",
            "XI_DEBOUNCE_EN",
            "XI_DEBOUNCE_POL",
            "XI_DEBOUNCE_T0",
            "XI_DEBOUNCE_T1",
            "XI_DEBUG_LEVEL",
            "XI_DECIMATION_HORIZONTAL",
            "XI_DECIMATION_PATTERN",
            "XI_DECIMATION_SELECTOR",
            "XI_DECIMATION_VERTICAL",
            "XI_DEFAULT_CC_MATRIX",
            "XI_DEVICE_MODEL_ID",
            "XI_DEVICE_RESET",
            "XI_DEVICE_SN",
            "XI_DOWNSAMPLING",
            "XI_DOWNSAMPLING_TYPE",
            "XI_EXPOSURE",
            "XI_EXPOSURE_BURST_COUNT",
            "XI_EXP_PRIORITY",
            "XI_FFS_ACCESS_KEY",
            "XI_FFS_FILE_ID",
            "XI_FFS_FILE_SIZE",
            "XI_FRAMERATE",
            "XI_FREE_FFS_SIZE",
            "XI_GAIN",
            "XI_GAIN_SELECTOR",
            "XI_GAMMAC",
            "XI_GAMMAY",
            "XI_GPI_LEVEL",
            "XI_GPI_MODE",
            "XI_GPI_SELECTOR",
            "XI_GPO_MODE",
            "XI_GPO_SELECTOR",
            "XI_HDR",
            "XI_HDR_KNEEPOINT_COUNT",
            "XI_HDR_T1",
            "XI_HDR_T2",
            "XI_HEIGHT",
            "XI_HOUS_BACK_SIDE_TEMP",
            "XI_HOUS_TEMP",
            "XI_HW_REVISION",
            "XI_IMAGE_BLACK_LEVEL",
            "XI_IMAGE_DATA_BIT_DEPTH",
            "XI_IMAGE_DATA_FORMAT",
            "XI_IMAGE_DATA_FORMAT_RGB32_ALPHA",
            "XI_IMAGE_IS_COLOR",
            "XI_IMAGE_PAYLOAD_SIZE",
            "XI_IS_COOLED",
            "XI_IS_DEVICE_EXIST",
            "XI_KNEEPOINT1",
            "XI_KNEEPOINT2",
            "XI_LED_MODE",
            "XI_LED_SELECTOR",
            "XI_LENS_APERTURE_VALUE",
            "XI_LENS_FEATURE",
            "XI_LENS_FEATURE_SELECTOR",
            "XI_LENS_FOCAL_LENGTH",
            "XI_LENS_FOCUS_DISTANCE",
            "XI_LENS_FOCUS_MOVE",
            "XI_LENS_FOCUS_MOVEMENT_VALUE",
            "XI_LENS_MODE",
            "XI_LIMIT_BANDWIDTH",
            "XI_LUT_EN",
            "XI_LUT_INDEX",
            "XI_LUT_VALUE",
            "XI_MANUAL_WB",
            "XI_OFFSET_X",
            "XI_OFFSET_Y",
            "XI_OUTPUT_DATA_BIT_DEPTH",
            "XI_OUTPUT_DATA_PACKING",
            "XI_OUTPUT_DATA_PACKING_TYPE",
            "XI_RECENT_FRAME",
            "XI_REGION_MODE",
            "XI_REGION_SELECTOR",
            "XI_ROW_FPN_CORRECTION",
            "XI_SENSOR_BOARD_TEMP",
            "XI_SENSOR_CLOCK_FREQ_HZ",
            "XI_SENSOR_CLOCK_FREQ_INDEX",
            "XI_SENSOR_DATA_BIT_DEPTH",
            "XI_SENSOR_FEATURE_SELECTOR",
            "XI_SENSOR_FEATURE_VALUE",
            "XI_SENSOR_MODE",
            "XI_SENSOR_OUTPUT_CHANNEL_COUNT",
            "XI_SENSOR_TAPS",
            "XI_SHARPNESS",
            "XI_SHUTTER_TYPE",
            "XI_TARGET_TEMP",
            "XI_TEST_PATTERN",
            "XI_TEST_PATTERN_GENERATOR_SELECTOR",
            "XI_TIMEOUT",
            "XI_TRANSPORT_PIXEL_FORMAT",
            "XI_TRG_DELAY",
            "XI_TRG_SELECTOR",
            "XI_TRG_SOFTWARE",
            "XI_TRG_SOURCE",
            "XI_TS_RST_MODE",
            "XI_TS_RST_SOURCE",
            "XI_USED_FFS_SIZE",
            "XI_WB_KB",
            "XI_WB_KG",
            "XI_WB_KR",
            "XI_WIDTH",
            "ZOOM"
            ]
    return list_of_property[id]


def make_multi_trackbar(list_of_property):
    for property in list_of_property:
        cv.createTrackbar(property[0],'Camera_Settings',int(property[1]),property[2],get_value)


def get_value(int):
    value = []
    for property in property_list:
        value.append(cv.getTrackbarPos(property[0],'Camera_Settings'))
    
    print(value)
    return set_prop(value)
    
        
def callback(x):
    pass


def set_prop(value):
    for id in range(len(control_parm)):
        try:
            cap.set(control_parm[id], value[id]/100)
        except Exception as e:
            print(name(id))
            return False




global property_list
global property_list_cv
global control_parm

property_list_cv = [
cv.CAP_PROP_AUTO_EXPOSURE,
cv.CAP_PROP_AUTO_WB,
cv.CAP_PROP_BACKEND,
cv.CAP_PROP_BACKLIGHT,
cv.CAP_PROP_BITRATE,
cv.CAP_PROP_BRIGHTNESS,
cv.CAP_PROP_BUFFERSIZE,
cv.CAP_PROP_CHANNEL,
cv.CAP_PROP_CODEC_PIXEL_FORMAT,
cv.CAP_PROP_CONTRAST,
cv.CAP_PROP_CONVERT_RGB,
cv.CAP_PROP_DC1394_MAX,
cv.CAP_PROP_DC1394_MODE_AUTO,
cv.CAP_PROP_DC1394_MODE_MANUAL,
cv.CAP_PROP_DC1394_MODE_ONE_PUSH_AUTO,
cv.CAP_PROP_DC1394_OFF,
cv.CAP_PROP_EXPOSURE,
cv.CAP_PROP_EXPOSUREPROGRAM,
cv.CAP_PROP_FOCUS,
cv.CAP_PROP_FORMAT,
cv.CAP_PROP_FOURCC,
cv.CAP_PROP_FPS,
cv.CAP_PROP_FRAME_COUNT,
cv.CAP_PROP_FRAME_HEIGHT,
cv.CAP_PROP_FRAME_WIDTH,
cv.CAP_PROP_GAIN,
cv.CAP_PROP_GAMMA,
cv.CAP_PROP_GIGA_FRAME_HEIGH_MAX,
cv.CAP_PROP_GIGA_FRAME_OFFSET_X,
cv.CAP_PROP_GIGA_FRAME_OFFSET_Y,
cv.CAP_PROP_GIGA_FRAME_SENS_HEIGH,
cv.CAP_PROP_GIGA_FRAME_SENS_WIDTH,
cv.CAP_PROP_GIGA_FRAME_WIDTH_MAX,
cv.CAP_PROP_GPHOTO2_COLLECT_MSGS,
cv.CAP_PROP_GPHOTO2_FLUSH_MSGS,
cv.CAP_PROP_GPHOTO2_PREVIEW,
cv.CAP_PROP_GPHOTO2_RELOAD_CONFIG,
cv.CAP_PROP_GPHOTO2_RELOAD_ON_CHANGE,
cv.CAP_PROP_GPHOTO2_WIDGET_ENUMERATE,
cv.CAP_PROP_GSTREAMER_QUEUE_LENGTH,
cv.CAP_PROP_GUID,
cv.CAP_PROP_HUE,
cv.CAP_PROP_IMAGES_BASE,
cv.CAP_PROP_IMAGES_LAST,
cv.CAP_PROP_INTELPERC_DEPTH_CONFIDENCE_THRESHOLD,
cv.CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_HORZ,
cv.CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_VERT,
cv.CAP_PROP_INTELPERC_DEPTH_LOW_CONFIDENCE_VALUE,
cv.CAP_PROP_INTELPERC_DEPTH_SATURATION_VALUE,
cv.CAP_PROP_INTELPERC_PROFILE_COUNT,
cv.CAP_PROP_INTELPERC_PROFILE_IDX,
cv.CAP_PROP_IOS_DEVICE_EXPOSURE,
cv.CAP_PROP_IOS_DEVICE_FLASH,
cv.CAP_PROP_IOS_DEVICE_FOCUS,
cv.CAP_PROP_IOS_DEVICE_TORCH,
cv.CAP_PROP_IOS_DEVICE_WHITEBALANCE,
cv.CAP_PROP_IRIS,
cv.CAP_PROP_ISO_SPEED,
cv.CAP_PROP_MODE,
cv.CAP_PROP_MONOCHROME,
cv.CAP_PROP_OPENNI2_MIRROR,
cv.CAP_PROP_OPENNI2_SYNC,
cv.CAP_PROP_OPENNI_APPROX_FRAME_SYNC,
cv.CAP_PROP_OPENNI_BASELINE,
cv.CAP_PROP_OPENNI_CIRCLE_BUFFER,
cv.CAP_PROP_OPENNI_FOCAL_LENGTH,
cv.CAP_PROP_OPENNI_FRAME_MAX_DEPTH,
cv.CAP_PROP_OPENNI_GENERATOR_PRESENT,
cv.CAP_PROP_OPENNI_MAX_BUFFER_SIZE,
cv.CAP_PROP_OPENNI_MAX_TIME_DURATION,
cv.CAP_PROP_OPENNI_OUTPUT_MODE,
cv.CAP_PROP_OPENNI_REGISTRATION,
cv.CAP_PROP_OPENNI_REGISTRATION_ON,
cv.CAP_PROP_PAN,
cv.CAP_PROP_POS_AVI_RATIO,
cv.CAP_PROP_POS_FRAMES,
cv.CAP_PROP_POS_MSEC,
cv.CAP_PROP_PVAPI_BINNINGX,
cv.CAP_PROP_PVAPI_BINNINGY,
cv.CAP_PROP_PVAPI_DECIMATIONHORIZONTAL,
cv.CAP_PROP_PVAPI_DECIMATIONVERTICAL,
cv.CAP_PROP_PVAPI_FRAMESTARTTRIGGERMODE,
cv.CAP_PROP_PVAPI_MULTICASTIP,
cv.CAP_PROP_PVAPI_PIXELFORMAT,
cv.CAP_PROP_RECTIFICATION,
cv.CAP_PROP_ROLL,
cv.CAP_PROP_SAR_DEN,
cv.CAP_PROP_SAR_NUM,
cv.CAP_PROP_SATURATION,
cv.CAP_PROP_SETTINGS,
cv.CAP_PROP_SHARPNESS,
cv.CAP_PROP_SPEED,
cv.CAP_PROP_TEMPERATURE,
cv.CAP_PROP_TILT,
cv.CAP_PROP_TRIGGER,
cv.CAP_PROP_TRIGGER_DELAY,
cv.CAP_PROP_VIEWFINDER,
cv.CAP_PROP_WB_TEMPERATURE,
cv.CAP_PROP_WHITE_BALANCE_BLUE_U,
cv.CAP_PROP_WHITE_BALANCE_RED_V,
cv.CAP_PROP_XI_ACQ_BUFFER_SIZE,
cv.CAP_PROP_XI_ACQ_BUFFER_SIZE_UNIT,
cv.CAP_PROP_XI_ACQ_FRAME_BURST_COUNT,
cv.CAP_PROP_XI_ACQ_TIMING_MODE,
cv.CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_COMMIT,
cv.CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_SIZE,
cv.CAP_PROP_XI_AEAG,
cv.CAP_PROP_XI_AEAG_LEVEL,
cv.CAP_PROP_XI_AEAG_ROI_HEIGHT,
cv.CAP_PROP_XI_AEAG_ROI_OFFSET_X,
cv.CAP_PROP_XI_AEAG_ROI_OFFSET_Y,
cv.CAP_PROP_XI_AEAG_ROI_WIDTH,
cv.CAP_PROP_XI_AE_MAX_LIMIT,
cv.CAP_PROP_XI_AG_MAX_LIMIT,
cv.CAP_PROP_XI_APPLY_CMS,
cv.CAP_PROP_XI_AUTO_BANDWIDTH_CALCULATION,
cv.CAP_PROP_XI_AUTO_WB,
cv.CAP_PROP_XI_AVAILABLE_BANDWIDTH,
cv.CAP_PROP_XI_BINNING_HORIZONTAL,
cv.CAP_PROP_XI_BINNING_PATTERN,
cv.CAP_PROP_XI_BINNING_SELECTOR,
cv.CAP_PROP_XI_BINNING_VERTICAL,
cv.CAP_PROP_XI_BPC,
cv.CAP_PROP_XI_BUFFERS_QUEUE_SIZE,
cv.CAP_PROP_XI_BUFFER_POLICY,
cv.CAP_PROP_XI_CC_MATRIX_00,
cv.CAP_PROP_XI_CC_MATRIX_01,
cv.CAP_PROP_XI_CC_MATRIX_02,
cv.CAP_PROP_XI_CC_MATRIX_03,
cv.CAP_PROP_XI_CC_MATRIX_10,
cv.CAP_PROP_XI_CC_MATRIX_11,
cv.CAP_PROP_XI_CC_MATRIX_12,
cv.CAP_PROP_XI_CC_MATRIX_13,
cv.CAP_PROP_XI_CC_MATRIX_20,
cv.CAP_PROP_XI_CC_MATRIX_21,
cv.CAP_PROP_XI_CC_MATRIX_22,
cv.CAP_PROP_XI_CC_MATRIX_23,
cv.CAP_PROP_XI_CC_MATRIX_30,
cv.CAP_PROP_XI_CC_MATRIX_31,
cv.CAP_PROP_XI_CC_MATRIX_32,
cv.CAP_PROP_XI_CC_MATRIX_33,
cv.CAP_PROP_XI_CHIP_TEMP,
cv.CAP_PROP_XI_CMS,
cv.CAP_PROP_XI_COLOR_FILTER_ARRAY,
cv.CAP_PROP_XI_COLUMN_FPN_CORRECTION,
cv.CAP_PROP_XI_COOLING,
cv.CAP_PROP_XI_COUNTER_SELECTOR,
cv.CAP_PROP_XI_COUNTER_VALUE,
cv.CAP_PROP_XI_DATA_FORMAT,
cv.CAP_PROP_XI_DEBOUNCE_EN,
cv.CAP_PROP_XI_DEBOUNCE_POL,
cv.CAP_PROP_XI_DEBOUNCE_T0,
cv.CAP_PROP_XI_DEBOUNCE_T1,
cv.CAP_PROP_XI_DEBUG_LEVEL,
cv.CAP_PROP_XI_DECIMATION_HORIZONTAL,
cv.CAP_PROP_XI_DECIMATION_PATTERN,
cv.CAP_PROP_XI_DECIMATION_SELECTOR,
cv.CAP_PROP_XI_DECIMATION_VERTICAL,
cv.CAP_PROP_XI_DEFAULT_CC_MATRIX,
cv.CAP_PROP_XI_DEVICE_MODEL_ID,
cv.CAP_PROP_XI_DEVICE_RESET,
cv.CAP_PROP_XI_DEVICE_SN,
cv.CAP_PROP_XI_DOWNSAMPLING,
cv.CAP_PROP_XI_DOWNSAMPLING_TYPE,
cv.CAP_PROP_XI_EXPOSURE,
cv.CAP_PROP_XI_EXPOSURE_BURST_COUNT,
cv.CAP_PROP_XI_EXP_PRIORITY,
cv.CAP_PROP_XI_FFS_ACCESS_KEY,
cv.CAP_PROP_XI_FFS_FILE_ID,
cv.CAP_PROP_XI_FFS_FILE_SIZE,
cv.CAP_PROP_XI_FRAMERATE,
cv.CAP_PROP_XI_FREE_FFS_SIZE,
cv.CAP_PROP_XI_GAIN,
cv.CAP_PROP_XI_GAIN_SELECTOR,
cv.CAP_PROP_XI_GAMMAC,
cv.CAP_PROP_XI_GAMMAY,
cv.CAP_PROP_XI_GPI_LEVEL,
cv.CAP_PROP_XI_GPI_MODE,
cv.CAP_PROP_XI_GPI_SELECTOR,
cv.CAP_PROP_XI_GPO_MODE,
cv.CAP_PROP_XI_GPO_SELECTOR,
cv.CAP_PROP_XI_HDR,
cv.CAP_PROP_XI_HDR_KNEEPOINT_COUNT,
cv.CAP_PROP_XI_HDR_T1,
cv.CAP_PROP_XI_HDR_T2,
cv.CAP_PROP_XI_HEIGHT,
cv.CAP_PROP_XI_HOUS_BACK_SIDE_TEMP,
cv.CAP_PROP_XI_HOUS_TEMP,
cv.CAP_PROP_XI_HW_REVISION,
cv.CAP_PROP_XI_IMAGE_BLACK_LEVEL,
cv.CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH,
cv.CAP_PROP_XI_IMAGE_DATA_FORMAT,
cv.CAP_PROP_XI_IMAGE_DATA_FORMAT_RGB32_ALPHA,
cv.CAP_PROP_XI_IMAGE_IS_COLOR,
cv.CAP_PROP_XI_IMAGE_PAYLOAD_SIZE,
cv.CAP_PROP_XI_IS_COOLED,
cv.CAP_PROP_XI_IS_DEVICE_EXIST,
cv.CAP_PROP_XI_KNEEPOINT1,
cv.CAP_PROP_XI_KNEEPOINT2,
cv.CAP_PROP_XI_LED_MODE,
cv.CAP_PROP_XI_LED_SELECTOR,
cv.CAP_PROP_XI_LENS_APERTURE_VALUE,
cv.CAP_PROP_XI_LENS_FEATURE,
cv.CAP_PROP_XI_LENS_FEATURE_SELECTOR,
cv.CAP_PROP_XI_LENS_FOCAL_LENGTH,
cv.CAP_PROP_XI_LENS_FOCUS_DISTANCE,
cv.CAP_PROP_XI_LENS_FOCUS_MOVE,
cv.CAP_PROP_XI_LENS_FOCUS_MOVEMENT_VALUE,
cv.CAP_PROP_XI_LENS_MODE,
cv.CAP_PROP_XI_LIMIT_BANDWIDTH,
cv.CAP_PROP_XI_LUT_EN,
cv.CAP_PROP_XI_LUT_INDEX,
cv.CAP_PROP_XI_LUT_VALUE,
cv.CAP_PROP_XI_MANUAL_WB,
cv.CAP_PROP_XI_OFFSET_X,
cv.CAP_PROP_XI_OFFSET_Y,
cv.CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH,
cv.CAP_PROP_XI_OUTPUT_DATA_PACKING,
cv.CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE,
cv.CAP_PROP_XI_RECENT_FRAME,
cv.CAP_PROP_XI_REGION_MODE,
cv.CAP_PROP_XI_REGION_SELECTOR,
cv.CAP_PROP_XI_ROW_FPN_CORRECTION,
cv.CAP_PROP_XI_SENSOR_BOARD_TEMP,
cv.CAP_PROP_XI_SENSOR_CLOCK_FREQ_HZ,
cv.CAP_PROP_XI_SENSOR_CLOCK_FREQ_INDEX,
cv.CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH,
cv.CAP_PROP_XI_SENSOR_FEATURE_SELECTOR,
cv.CAP_PROP_XI_SENSOR_FEATURE_VALUE,
cv.CAP_PROP_XI_SENSOR_MODE,
cv.CAP_PROP_XI_SENSOR_OUTPUT_CHANNEL_COUNT,
cv.CAP_PROP_XI_SENSOR_TAPS,
cv.CAP_PROP_XI_SHARPNESS,
cv.CAP_PROP_XI_SHUTTER_TYPE,
cv.CAP_PROP_XI_TARGET_TEMP,
cv.CAP_PROP_XI_TEST_PATTERN,
cv.CAP_PROP_XI_TEST_PATTERN_GENERATOR_SELECTOR,
cv.CAP_PROP_XI_TIMEOUT,
cv.CAP_PROP_XI_TRANSPORT_PIXEL_FORMAT,
cv.CAP_PROP_XI_TRG_DELAY,
cv.CAP_PROP_XI_TRG_SELECTOR,
cv.CAP_PROP_XI_TRG_SOFTWARE,
cv.CAP_PROP_XI_TRG_SOURCE,
cv.CAP_PROP_XI_TS_RST_MODE,
cv.CAP_PROP_XI_TS_RST_SOURCE,
cv.CAP_PROP_XI_USED_FFS_SIZE,
cv.CAP_PROP_XI_WB_KB,
cv.CAP_PROP_XI_WB_KG,
cv.CAP_PROP_XI_WB_KR,
cv.CAP_PROP_XI_WIDTH,
cv.CAP_PROP_ZOOM
]




property_list = []
control_parm = []

for (id, property) in enumerate(property_list_cv):
    
    con = cap.get(property)

    if con != -1:
        print(id," : ", name(id), " : ", property, con)
        property_list.append([name(id), con*100, 1000])
        control_parm.append(property)

        




cv.namedWindow('Camera_Settings')

make_multi_trackbar(property_list)

print(get_value(property_list))

while True:
    ret , frame = cap.read()
    cv.imshow('frame',frame)
    if cv.waitKey(1) & 0xFF == ord('q'):
        break


cv.waitKey(0)